workflow:
    rules:
        - if: $CI_COMMIT_TAG

stages:
    - test
    - build-and-push

test:
    stage: test
    image: node:16.6.0
    script:
        - npm ci --ignore-scripts
        - npm run prettier
        - npm run eslint
        - npm run test -- --watchAll=false
build-and-push:
    stage: build-and-push
    image: docker:19.03.15
    services:
        - docker:19.03.15-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:latest
