name: Github CI

on:
    push:
        tags: v*

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Install Dependencies
              run: npm ci --ignore-scripts
            - name: Run Formatting Checks
              run: npm run prettier
            - name: Run Linting Checks
              run: npm run eslint
            - name: Run Tests
              run: npm run test -- --watchAll=false
    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Login To Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Metadata
              uses: docker/metadata-action@v3
              id: meta
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=semver,pattern={{raw}}
            - name: Build And Push Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
